version: "3.9"

services:
  mongo:
    image: mongo:7.0-rc-jammy
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  postgres:
    image: postgres:16.0
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "3001:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    expose:
      - 3001


  springboot-app:
    build: .
    image: springboot-app
    ports:
      - "9080:8080"


    depends_on:
      - mongo
      - postgres

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
      MINIO_DEFAULT_BUCKETS: default-bucket
    volumes:
      - ./data:/data


volumes:
  mongo-data:
  postgres-data:

