version: "3.9"

services:
  mongo:
    image: mongo:7.0-rc-jammy
    expose:
      - 27017
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
  postgres:
    image: postgres:16.0

    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "3001:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    expose:
      - 3001
  # make sure the keycloak version matches with the dependency in pom.xml
  keycloak:
    image: quay.io/keycloak/keycloak:21.0.2
    expose:
      - 8081
    command: ["start-dev","--http-port=8081"]
    environment:
      DB_VENDOR: POSTGRES
      DB_PORT: 3001
      DB_ADDR: postgres
      DB_DATABASE: postgres
      DB_USER: postgres
      DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8081:8081"
    depends_on:
      - postgres



  springboot-app:
    build: .
    image: springboot-app
    expose:
      - 8080
    ports:
      - "8080:8080"


    depends_on:
      - mongo

      - postgres
       
      - minio
      - keycloak


  minio:
    image: minio/minio:RELEASE.2024-01-18T22-51-28Z-cpuv1
    command: server /data --console-address ":9001"

    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
      MINIO_DEFAULT_BUCKETS: default-bucket
    volumes:
      - ./data:/data


volumes:
  mongo-data:
  postgres-data:

