version: "3.9"

services:
  mongo:
    image: mongo:7.0-rc-jammy
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  postgres:
    image: postgres:16.0
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    expose:
      - 5433


  springboot-app:
    build: .
    image: springboot-app
    ports:
      - "9080:8080"


    depends_on:
      - mongo
      - postgres


volumes:
  mongo-data:
  postgres-data:
