version: "3.9"

services:
  mongo:
    image: mongo:7.0-rc-jammy
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
  postgres:
    image: postgres:16.0
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "3001:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    expose:
      - 3001
  keycloak:
    image: quay.io/keycloak/keycloak:21.0.2
    command: start-dev
    environment:
      DB_VENDOR: POSTGRES
      DB_PORT: 3001
      DB_ADDR: postgres
      DB_DATABASE: postgres
      DB_USER: postgres
      DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8081:8080"
    depends_on:
      - postgres



  springboot-app:
    build: .
    image: springboot-app
    ports:
      - "8080:8080"


    depends_on:
        mongo:
          condition: service_completed_successfully
        postgres:
          condition: service_completed_successfully
        minio:
          condition: service_completed_successfully

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
      MINIO_DEFAULT_BUCKETS: default-bucket
    volumes:
      - ./data:/data


volumes:
  mongo-data:
  postgres-data:

